// <auto-generated />
namespace Sudoku.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Talk_Update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Talk_Update));
        
        string IMigrationMetadata.Id
        {
            get { return "201712100912592_Talk_Update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
